FROM golang:1.25.3 AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build -o server ./cmd/studio/main.go

FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /build/server /app/server
COPY --from=builder /build/accounts.json /app/accounts.json

EXPOSE 8080

CMD ["/app/server"]
